In [3]:
import json
import pandas as pd
import os

#Loading data
f = open(os.path.join(os.getcwd(), "..", "json", "playlists.json"))
data = json.load(f)

#Experimenting with datatypes
print(type(data) == dict)
print(type(data["categories"]) == list)
print(type(data["categories"][0]["playlists"]))
print(type(data["categories"][0]["playlists"][0]["id"]))
#dict -> list -> dict -> list -> dict -> string

df_normalized = pd.json_normalize(data["categories"])
df_normalized
#only normalizes to first level

True
True
<class 'list'>
<class 'str'>

,id,name,playlists
0,toplists,Top Lists,"[{'id': '37i9dQZF1DXcBWIGoYBM5M', 'name': 'Tod..."
1,hiphop,Hip Hop,"[{'id': '37i9dQZF1DX0XUsuxWHRQd', 'name': 'Rap..."
2,pop,Pop,"[{'id': '37i9dQZF1DXcBWIGoYBM5M', 'name': 'Tod..."
3,country,Country,"[{'id': '37i9dQZF1DX1lVhptIYRda', 'name': 'Hot..."
4,rock,Rock,"[{'id': '37i9dQZF1DXcF6B6QPhFDv', 'name': 'Roc..."
5,latin,Latin,"[{'id': '37i9dQZF1DX10zKzsJ2jva', 'name': 'Â¡Vi..."
6,mood,Mood,"[{'id': '37i9dQZF1DX3rxVfibe1L0', 'name': 'Moo..."
7,workout,Workout,"[{'id': '37i9dQZF1DX76Wlfdnj7AP', 'name': 'Bea..."
8,rnb,R&B,"[{'id': '37i9dQZF1DX4SBhb3fqCJd', 'name': 'Are..."
9,edm_dance,Dance/Electronic,"[{'id': '37i9dQZF1DX4dyzvuaRJ0n', 'name': 'min..."
10,indie_alt,Indie,"[{'id': '37i9dQZF1DX2Nc3B70tvx0', 'name': 'Ult..."
11,sleep,Sleep,"[{'id': '37i9dQZF1DWZd79rJ6a7lp', 'name': 'Sle..."
12,regional_mexican,Regional Mexican,"[{'id': '37i9dQZF1DXb0COFso7q0D', 'name': 'Los..."
13,chill,Chill,"[{'id': '37i9dQZF1DWTwnEm1IYyoj', 'name': 'Sof..."
14,inspirational,Christian & Gospel,"[{'id': '37i9dQZF1DWVtgG63SDdt8', 'name': 'New..."
15,frequency,Frequency,"[{'id': '37i9dQZF1DWVgsJtp58d1t', 'name': 'Thi..."
16,decades,Decades,"[{'id': '37i9dQZF1DX4UtSsGT1Sbe', 'name': 'All..."
17,fresh_finds,Fresh Finds,"[{'id': '37i9dQZF1DWWjGdmeTyeJ6', 'name': 'Fre..."
18,student,Student,"[{'id': '37i9dQZF1DX3csziQj0d5b', 'name': 'hom..."
19,focus,Focus,"[{'id': '37i9dQZF1DWZeKCadgRdKQ', 'name': 'Dee..."
20,equal,EQUAL,"[{'id': '37i9dQZF1DWU8quswnFt3c', 'name': 'EQU..."
21,party,Party,"[{'id': '37i9dQZF1DXa2PvUpywmrr', 'name': 'Par..."
22,kids_family,Kids & Family,"[{'id': '37i9dQZF1DX6r25lY14UGk', 'name': 'toy..."
23,gaming,Gaming,"[{'id': '37i9dQZF1DWTyiBJ6yEqeu', 'name': 'Top..."
24,roots,Folk & Acoustic,"[{'id': '37i9dQZF1DXaUDcU6KDCj4', 'name': 'Fre..."
25,kpop,K-Pop,"[{'id': '37i9dQZF1DX5JcPJgYjGcf', 'name': 'Thi..."
26,instrumental,Instrumental,"[{'id': '37i9dQZF1DX4sWSpwq3LiO', 'name': 'Pea..."
27,ambient,Ambient,"[{'id': '37i9dQZF1DWUrPBdYfoJvz', 'name': 'Amb..."
28,alternative,Alternative,"[{'id': '37i9dQZF1DX82GYcclJ3Ug', 'name': 'The..."
29,wellness,Wellness,"[{'id': '37i9dQZF1DX9uKNf5jGX6m', 'name': 'Yog..."
30,pride,Pride,"[{'id': '37i9dQZF1DX3LyU0mhfqgP', 'name': 'Out..."
31,romance,Romance,"[{'id': '37i9dQZF1DX7gIoKXt0gmx', 'name': 'All..."
32,in_the_car,In the car,"[{'id': '37i9dQZF1DWWMOmoXKqHTD', 'name': 'Son..."
33,shows_with_music,theLINER,[]
34,classical,Classical,"[{'id': '37i9dQZF1DWWEJlAGA9gs0', 'name': 'Cla..."
35,jazz,Jazz,"[{'id': '37i9dQZF1DWW2c0C8Vb2IR', 'name': 'All..."
36,soul,Soul,"[{'id': '37i9dQZF1DX3z6D2ln0Hqx', 'name': 'Wom..."
37,sessions,Spotify Singles,"[{'id': '37i9dQZF1DWVP71DYelp29', 'name': 'Spo..."
38,at_home,At Home,"[{'id': '37i9dQZF1DWTLSN7iG21yC', 'name': 'Wor..."
39,dinner,Cooking & Dining,"[{'id': '37i9dQZF1DXbm6HfkbMtFZ', 'name': 'Fee..."
40,punk,Punk,"[{'id': '37i9dQZF1DX0KpeLFwA3tO', 'name': 'New..."
41,sports,Sports,"[{'id': '37i9dQZF1DXdxTsNp0Bzwq', 'name': 'Gam..."
42,popculture,Pop culture,"[{'id': '37i9dQZF1DWYNNUgvFqsgZ', 'name': 'KIN..."
43,aapi_heritage_month,Stop Asian Hate,"[{'id': '37i9dQZF1DX5IOhx43PGIa', 'name': 'Jas..."
44,blues,Blues,"[{'id': '37i9dQZF1DX0QNpebF7rcL', 'name': 'Got..."
45,arab,Arab,"[{'id': '37i9dQZF1DX5cO1uP1XC1g', 'name': 'Top..."
46,desi,Desi,[]
47,radar,RADAR,"[{'id': '37i9dQZF1DWY0DyDKedRYY', 'name': 'RAD..."
48,jre_podcast,Joe Rogan Experience,"[{'id': '37i9dQZF1DXa8nzolwWuPH', 'name': 'Ins..."
49,callherdaddy_podcast,Call Her Daddy,"[{'id': '37i9dQZF1DXctxtzTIbh1L', 'name': 'Ale..."
50,anime,Anime,"[{'id': '37i9dQZF1DWT8aqnwgRt92', 'name': 'Ani..."
51,thirdparty,Tastemakers,[]
52,afro,Afro,"[{'id': '37i9dQZF1DWYkaDif7Ztbp', 'name': 'Afr..."
53,comedy,Comedy,[]
54,metal,Metal,"[{'id': '37i9dQZF1DWTcqUzwhNmKv', 'name': 'Kic..."
55,caribbean,Caribbean,"[{'id': '37i9dQZF1DWX1DwkjCqoyw', 'name': 'Isl..."
56,funk,Funk & Disco,"[{'id': '37i9dQZF1DWZgauS5j6pMv', 'name': 'Nu-..."
57,holidays,Happy Holidays,"[{'id': '37i9dQZF1DX0Yxoavh5qJV', 'name': 'Chr..."

In [4]:
#recursive function to flatten json
def flatten_json(y):
    out = {}

    def flatten(x, name=''):
        if type(x) is dict:
            for a in x:
                flatten(x[a], name + a + '.')
        elif type(x) is list:
            i = 0
            for a in x:
                flatten(a, name + str(i) + '.')
                i += 1
        else:
            out[name[:-1]] = x

    flatten(y)
    return out

flat_json = flatten_json(data["categories"])
#with open(os.path.join(os.getcwd(), "json", "flat.json"), 'w') as outfile:
#    json.dump(data, outfile, indent=2)
df_flattened = pd.json_normalize(flat_json)
df_flattened
#format not usable like this

,0.id,0.name,0.playlists.0.id,0.playlists.0.name,0.playlists.1.id,0.playlists.1.name,0.playlists.2.id,0.playlists.2.name,0.playlists.3.id,0.playlists.3.name,...,57.playlists.54.id,57.playlists.54.name,57.playlists.55.id,57.playlists.55.name,57.playlists.56.id,57.playlists.56.name,57.playlists.57.id,57.playlists.57.name,57.playlists.58.id,57.playlists.58.name
0,toplists,Top Lists,37i9dQZF1DXcBWIGoYBM5M,Today's Top Hits,37i9dQZF1DX0XUsuxWHRQd,RapCaviar,37i9dQZF1DXcF6B6QPhFDv,Rock This,37i9dQZF1DX4dyzvuaRJ0n,mint,...,37i9dQZF1DWWT5IouU5EAl,Natal Ã Portuguesa,37i9dQZF1DX8c93KtGDPub,Folksy Christmas,37i9dQZF1DWTZ37yWkEort,A Cappella Christmas,37i9dQZF1DX3lQi4RhMuwd,This is Mariah Carey,37i9dQZF1DX2zhLcnFr1qI,Electronic Christmas

In [8]:

# Solution using code from stackoverflow
# https://stackoverflow.com/questions/52795561/flattening-nested-json-in-pandas-data-frame
# Currently doesn't support multiple nested dicts

# normalize events
df_1 = pd.json_normalize(data, 'categories')

# explode all columns with lists of dicts
df_1 = df_1.apply(lambda x: x.explode()).reset_index(drop=True)

# list of columns with dicts
cols_to_normalize = ['playlists']

# if there are keys, which will become column names, overlap with excising column names
# add the current column name as a prefix
normalized = list()
for col in cols_to_normalize:
    
    d = pd.json_normalize(df_1[col], sep='_')
    d.columns = [f'{col}_{v}' for v in d.columns]
    normalized.append(d.copy())

# combine df with the normalized columns
df_1 = pd.concat([df_1] + normalized, axis=1).drop(columns=cols_to_normalize)
df_1

            id            name            playlists_id        playlists_name
0     toplists       Top Lists  37i9dQZF1DXcBWIGoYBM5M      Today's Top Hits
1     toplists       Top Lists  37i9dQZF1DX0XUsuxWHRQd             RapCaviar
2     toplists       Top Lists  37i9dQZF1DXcF6B6QPhFDv             Rock This
3     toplists       Top Lists  37i9dQZF1DX4dyzvuaRJ0n                  mint
4     toplists       Top Lists  37i9dQZF1DX1lVhptIYRda           Hot Country
...        ...             ...                     ...                   ...
3043  holidays  Happy Holidays  37i9dQZF1DWWT5IouU5EAl    Natal Ã  Portuguesa
3044  holidays  Happy Holidays  37i9dQZF1DX8c93KtGDPub      Folksy Christmas
3045  holidays  Happy Holidays  37i9dQZF1DWTZ37yWkEort  A Cappella Christmas
3046  holidays  Happy Holidays  37i9dQZF1DX3lQi4RhMuwd  This is Mariah Carey
3047  holidays  Happy Holidays  37i9dQZF1DX2zhLcnFr1qI  Electronic Christmas

[3048 rows x 4 columns]